name: release
version: 0.4.1
usage: pull or update Helm Releases
description: Update values of releases, pull charts from releases
platformCommand:
  command: $HELM_PLUGIN_DIR/release.sh
platformHooks:
  install:
    command: >
      VERSION=$(curl --silent "https://api.github.com/repos/mikefarah/yq/releases/latest" | jq -r .tag_name)
      OS="$(uname | tr '[:upper:]' '[:lower:]')"

      case $OS in
        darwin*)  BINARY="yq_darwin_amd64" ;;
        linux*)   BINARY="yq_linux_amd64" ;;
        *)        echo "Unsupported operating system ($OS) detected while installing yq." >&2; exit 1 ;;
      esac

      mkdir -p "{$HELM_PLUGIN_DIR}/lib"
      curl -L "https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}" -o "$HELM_PLUGIN_DIR/lib/yq"
      chmod +x "${HELM_PLUGIN_DIR}/lib/yq"
